name: Deploy to Vercel

on:
  # 当update-cursor-links.yml工作流完成时触发
  workflow_run:
    workflows: ["Update Cursor Download Links"]
    types:
      - completed
  # 允许手动触发
  workflow_dispatch:

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史以便比较

      - name: Check for version changes
        id: check_changes
        run: |
          # 检查最近的提交是否修改了version-history.json
          if git log -1 --name-only | grep -q "version-history.json"; then
            echo "found_changes=true" >> $GITHUB_OUTPUT
            echo "New version detected, will deploy to Vercel"
          else
            echo "found_changes=false" >> $GITHUB_OUTPUT
            echo "No new version detected, skipping deployment"
          fi

      # 设置Node.js环境
      - name: Setup Node.js
        if: steps.check_changes.outputs.found_changes == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 复制version-history.json到web项目
      - name: Copy data to web project
        if: steps.check_changes.outputs.found_changes == 'true'
        run: |
          node src/update-web-data.js

      # 部署到Vercel
      - name: Deploy to Vercel
        if: steps.check_changes.outputs.found_changes == 'true'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod' 